name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - uses: actions/checkout@v1

      - name: Build
        run: |
          go install github.com/newrelic/go-agent/v3/newrelic
          go build -v .
